# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Virtual_Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Infra', models.CharField(blank=True, max_length=200, null=True)),
                ('Function', models.CharField(blank=True, max_length=200, null=True)),
                ('Business_Owner', models.CharField(blank=True, max_length=200, null=True)),
                ('Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('Faculty', models.CharField(blank=True, max_length=200, null=True)),
                ('Contribution', models.CharField(blank=True, max_length=200, null=True)),
                ('Nominated_Admins', models.CharField(blank=True, max_length=200, null=True)),
                ('Isilon', models.CharField(blank=True, max_length=200, null=True)),
                ('Sensitive_Data', models.CharField(blank=True, max_length=200, null=True)),
                ('Type', models.CharField(blank=True, max_length=200, null=True)),
                ('OS', models.CharField(blank=True, max_length=200, null=True)),
                ('CPUcores', models.CharField(blank=True, max_length=200, null=True)),
                ('Memory', models.CharField(blank=True, max_length=200, null=True)),
                ('HDD', models.CharField(blank=True, max_length=200, null=True)),
                ('DNS', models.URLField(blank=True, null=True)),
                ('IP_Address', models.GenericIPAddressField(blank=True, null=True)),
                ('Sysadmin1', models.CharField(blank=True, max_length=200, null=True)),
                ('Sysadmin2', models.CharField(blank=True, max_length=200, null=True)),
                ('Reference', models.CharField(blank=True, max_length=200, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
