# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtual_machine',
            name='Deployment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEV', 'Development'), ('ARC', 'Archived')], default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtual_machine',
            name='Test',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='virtual_machine',
            name='Infra',
            field=models.CharField(choices=[('RVMI', 'Research VM Infra'), ('BS', 'Business VM Infra')], default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='virtual_machine',
            name='Sensitive_Data',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
