# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_auto_20170427_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtual_machine',
            name='Deployment',
            field=models.CharField(choices=[('Production', 'Production'), ('Development', 'Development'), ('Archived', 'Archived')], max_length=20),
        ),
        migrations.AlterField(
            model_name='virtual_machine',
            name='Infra',
            field=models.CharField(choices=[('RVMI', 'Research VM Infra'), ('BS', 'Business VM Infra')], max_length=20),
        ),
        migrations.AlterField(
            model_name='virtual_machine',
            name='Sensitive_Data',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20),
        ),
    ]
